[package]
name = "fanout-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.50.0"
axum = { version = "0.8.9", features = ["ws"] }
config = "0.15.25"
dashmap = "6.2.1"
domain = { version = "0.1.0", path = "../domain" }
dotenvy = "0.15.7"
infra = { version = "0.1.0", path = "../infra" }
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
